
.. csv-table:: [Autogenerated table scheme of table "wp_wetterturnier_dates] Wetterturnier calendar dates. Definition of when tournaments will take place/took place."
    :header: "Field", "Type", "Null", "Key", "Default", "Extra"

    "tdate","smallint(11) unsigned","NO","PRI","None",""
    "status","tinyint(4)","NO","","1",""



* **Unique-key** named *PRIMARY* on ``(tdate)``


