CREATE TABLE %table% (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    cityID SMALLINT UNSIGNED NOT NULL,
    tdate  SMALLINT UNSIGNED NOT NULL,
    userID BIGINT UNSIGNED NOT NULL,
    placed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    done TIMESTAMP NULL,
    PRIMARY KEY (ID)
);



